
name = "DashSpreadGrid"
uuid = "1b08a953-4be3-4667-9a23-1396e3efe802"
authors = ["Tomasz Rewak <tomasz.rewak@gmail.com>"]
version = "0.1.13"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
